using System.Text;
using Charisma.Generator.Writers;
using Charisma.Schema;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Charisma.Generator;
/// <summary>
/// Entry point for Phase 1 code generation.
/// Responsible for writer orchestration, header construction,
/// deterministic file naming, and file IO.
/// </summary>
public sealed class CharismaGenerator : ICharismaGenerator
{
    private readonly GeneratorOptions _options;
    private IReadOnlyList<IWriter> _writers { get; set; }
    /// <summary>
    /// Creates a new Phase 1 generator.
    /// </summary>
    public CharismaGenerator(
        GeneratorOptions options)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
        var writers = new List<IWriter>
            {
                new EnumWriter(_options.RootNamespace),
                new ModelWriter(_options.RootNamespace),
                new DelegateWriter(_options.RootNamespace),
                new MetadataWriter(_options.RootNamespace),
                new ArgsWriter(_options.RootNamespace),
                new FilterWriter(_options.RootNamespace),
                new SelectWriter(_options.RootNamespace),
                new OmitWriter(_options.RootNamespace),
                new IncludeWriter(_options.RootNamespace),
                new ClientWriter(_options.RootNamespace)
            };
        _writers = writers.AsReadOnly();
    }

    /// <summary>
    /// Executes Phase 1 code generation.
    /// </summary>
    /// <param name="schema">Parsed schema used to drive all writers.</param>
    /// <returns>Compilation units generated by all writers.</returns>
    public IReadOnlyList<CompilationUnitSyntax> Generate(CharismaSchema schema)
    {
        ArgumentNullException.ThrowIfNull(schema);

        // Phase 0 already computed this hash.
        var generatedHeader = BuildGeneratedHeader(schema.SchemaHash);

        Directory.CreateDirectory(_options.OutputDirectory);

        var results = new List<CompilationUnitSyntax>();

        foreach (var writer in _writers)
        {
            foreach (var unit in writer.Write(schema))
            {
                var path = FileNameDerivation.DerivePath(
                    _options.OutputDirectory,
                    unit);

                WriteCompilationUnit(path, unit, generatedHeader);
                results.Add(unit);
            }
        }

        return results;
    }

    /// <summary>
    /// Builds the fully resolved generated file header.
    /// Writers receive this header as an opaque string.
    /// </summary>
    /// <param name="schemaHash">Previously computed schema hash for traceability.</param>
    /// <returns>Auto-generated header text.</returns>
    private string BuildGeneratedHeader(string schemaHash)
    {
        return
            "// <auto-generated>\n" +
            $"// Generated by Charisma Generator v{_options.GeneratorVersion}\n" +
            $"// Schema Hash: {schemaHash}\n" +
            "// Do NOT edit this file manually.\n" +
            "// </auto-generated>\n\n";
    }

    /// <summary>
    /// Writes a CompilationUnitSyntax to disk with deterministic formatting.
    /// </summary>
    /// <param name="path">Target file path.</param>
    /// <param name="unit">Compilation unit to serialize.</param>
    /// <param name="header">Prepend header string (auto-generated notice and hash).</param>
    private static void WriteCompilationUnit(
        string path,
        CompilationUnitSyntax unit,
        string header)
    {
        var directory = Path.GetDirectoryName(path)!;
        Directory.CreateDirectory(directory);

        var code = unit.NormalizeWhitespace().ToFullString();
        var nullablePrelude = "#nullable enable\n\n";

        File.WriteAllText(
            path,
            header + nullablePrelude + code,
            Encoding.UTF8);
    }
}