using Charisma.Parser;
using Charisma.Schema;

namespace Charisma.Generator.Tests;

public sealed class GeneratorIntegrationTests
{
    private const string RootNamespace = "Charisma.Generated";

    [Fact]
    public void Constructor_NullOptions_Throws()
    {
        Assert.Throws<ArgumentNullException>(() => new CharismaGenerator(null!));
    }

    [Fact]
    public void Generate_NullSchema_Throws()
    {
        using var temp = new TempDirectory();
        var generator = CreateGenerator(temp.Path);
        Assert.Throws<ArgumentNullException>(() => generator.Generate(null!));
    }

    [Fact]
    public void Generate_MinimalPlaceholderSchema_WritesExpectedArtifactsAndHeaders()
    {
        const string schemaText = """
			model Robot {
			  RobotID Id @id
			  Naam String
			}
			""";

        using var temp = new TempDirectory();
        var schema = Parse(schemaText);
        var generator = CreateGenerator(temp.Path);

        var units = generator.Generate(schema);
        var generatedFiles = Directory.GetFiles(temp.Path, "*.cs", SearchOption.AllDirectories);

        Assert.NotEmpty(units);
        Assert.NotEmpty(generatedFiles);
        Assert.Contains(generatedFiles, f => f.EndsWith(Path.Combine("Models", "Robot.g.cs"), StringComparison.Ordinal));
        Assert.Contains(generatedFiles, f => f.EndsWith("CharismaClient.g.cs", StringComparison.Ordinal));

        foreach (var file in generatedFiles.Take(10))
        {
            var text = File.ReadAllText(file);
            Assert.Contains("// <auto-generated>", text);
            Assert.Contains($"// Schema Hash: {schema.SchemaHash}", text);
            Assert.Contains("#nullable enable", text);
        }
    }

    [Fact]
    public void Generate_ComplexPlaceholderSchema_CoversAllMajorOutputDirectories()
    {
        const string schemaText = """
			enum RobotStatus {
			  ACTIVE
			  IDLE
			}

			model Locatie {
			  LocatieID Id @id
			  Naam String
			  Robots Robot[]
			}

			model Robot {
			  RobotID Id @id
			  LocatieID Id?
			  Naam String
			  Status RobotStatus
			  Actief Boolean
			  Payload Json?
			  created_at DateTime

			  Locatie Locatie? @relation(fk: (Robot.LocatieID), pk: (Locatie.LocatieID))
			}
			""";

        using var temp = new TempDirectory();
        var schema = Parse(schemaText);
        var generator = CreateGenerator(temp.Path);
        generator.Generate(schema);

        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Args")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Delegates")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Enums")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Filters")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Include")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Metadata")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Models")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Omit")));
        Assert.True(Directory.Exists(Path.Combine(temp.Path, "Select")));

        Assert.True(File.Exists(Path.Combine(temp.Path, "Enums", "RobotStatus.g.cs")));
        Assert.True(File.Exists(Path.Combine(temp.Path, "Models", "Robot.g.cs")));
        Assert.True(File.Exists(Path.Combine(temp.Path, "Models", "Locatie.g.cs")));
        Assert.True(File.Exists(Path.Combine(temp.Path, "Delegates", "RobotDelegate.g.cs")));
        Assert.True(File.Exists(Path.Combine(temp.Path, "Metadata", "ModelMetadataRegistry.g.cs")));
    }

    [Fact]
    public void Generate_ManualScalarMatrix_MapsCriticalTypes()
    {
        using var temp = new TempDirectory();
        var schema = BuildManualSchema("ScalarMatrix", new FieldDefinition[]
        {
            new ScalarFieldDefinition("Id", "Id", false, false, ["@id"], isId: true),
            new ScalarFieldDefinition("Name", "String", false, false, []),
            new ScalarFieldDefinition("Count", "Int", false, false, []),
            new ScalarFieldDefinition("Enabled", "Boolean", false, false, []),
            new ScalarFieldDefinition("Ratio", "Float", false, false, []),
            new ScalarFieldDefinition("Price", "Decimal", false, false, []),
            new ScalarFieldDefinition("At", "DateTime", false, false, []),
            new ScalarFieldDefinition("Payload", "Json", false, true, []),
            new ScalarFieldDefinition("Raw", "Bytes", false, true, []),
            new ScalarFieldDefinition("Tags", "String", true, false, [])
        });

        var generator = CreateGenerator(temp.Path);
        generator.Generate(schema);

        var modelFile = Path.Combine(temp.Path, "Models", "ScalarMatrix.g.cs");
        var text = File.ReadAllText(modelFile);

        Assert.Contains("public Guid Id", text);
        Assert.Contains("public string Name", text);
        Assert.Contains("public int Count", text);
        Assert.Contains("public bool Enabled", text);
        Assert.Contains("public double Ratio", text);
        Assert.Contains("public decimal Price", text);
        Assert.Contains("public DateTime At", text);
        Assert.Contains("public Json? Payload", text);
        Assert.Contains("public byte[]? Raw", text);
        Assert.Contains("public IReadOnlyList<string> Tags", text);
    }

    [Fact]
    public void Generate_CompositeUniqueSelectors_AppearInWhereUniqueInput()
    {
        const string schemaText = """
			model Membership {
			  UserId Id
			  TeamId Id
			  Email String @unique
			  Role String
			  @@id(UserId, TeamId)
			}
			""";

        using var temp = new TempDirectory();
        var schema = Parse(schemaText);
        var generator = CreateGenerator(temp.Path);
        generator.Generate(schema);

        var filterFile = Path.Combine(temp.Path, "Filters", "MembershipFilter.g.cs");
        var text = File.ReadAllText(filterFile);

        Assert.Contains("public string? Email", text);
        Assert.Contains("public MembershipByUserIdAndTeamIdInput? ByUserIdAndTeamId", text);
        Assert.Contains("public partial class MembershipByUserIdAndTeamIdInput", text);
        Assert.Contains("public Guid? UserId", text);
        Assert.Contains("public Guid? TeamId", text);
    }

    [Fact]
    public void Generate_CompositePrimaryKeyDelegateConveniences_AreEmitted()
    {
        const string schemaText = """
			model Membership {
			  UserId Id
			  TeamId Id
			  Role String
			  @@id(UserId, TeamId)
			}
			""";

        using var temp = new TempDirectory();
        var schema = Parse(schemaText);
        var generator = CreateGenerator(temp.Path);
        generator.Generate(schema);

        var delegateFile = Path.Combine(temp.Path, "Delegates", "MembershipDelegate.g.cs");
        var text = File.ReadAllText(delegateFile);

        Assert.Contains("Task<Membership?> FindByKeyAsync", text);
        Assert.Contains("Task<Membership?> DeleteByKeyAsync", text);
        Assert.Contains("Task<Membership?> UpdateByKeyAsync", text);
        Assert.Contains("ByUserIdAndTeamId = new MembershipByUserIdAndTeamIdInput", text);
    }

    [Fact]
    public void Generate_SecondRun_RewritesModifiedOutputAndKeepsDeterministicContent()
    {
        const string schemaText = """
			model Locatie {
			  LocatieID Id @id
			  Naam String
			}
			""";

        using var temp = new TempDirectory();
        var schema = Parse(schemaText);
        var generator = CreateGenerator(temp.Path);

        generator.Generate(schema);

        var modelFile = Path.Combine(temp.Path, "Models", "Locatie.g.cs");
        var firstContent = File.ReadAllText(modelFile);

        File.AppendAllText(modelFile, "\n// MUTATION");
        Assert.Contains("MUTATION", File.ReadAllText(modelFile));

        generator.Generate(schema);
        var secondContent = File.ReadAllText(modelFile);

        Assert.Equal(firstContent, secondContent);
        Assert.DoesNotContain("MUTATION", secondContent);
    }

    [Fact]
    public void Generate_OutputPathPointsToExistingFile_ThrowsIOException()
    {
        using var temp = new TempDirectory();
        var outputPath = Path.Combine(temp.Path, "not-a-directory.txt");
        File.WriteAllText(outputPath, "x");

        var schema = Parse("""
			model A {
			  id Id @id
			}
			""");

        var generator = CreateGenerator(outputPath);
        Assert.Throws<IOException>(() => generator.Generate(schema));
    }

    [Fact]
    public void Generate_UnsupportedScalarTypeInManualSchema_ThrowsInvalidOperationException()
    {
        using var temp = new TempDirectory();
        var schema = BuildManualSchema("Broken", new FieldDefinition[]
        {
            new ScalarFieldDefinition("Id", "Id", false, false, ["@id"], isId: true),
            new ScalarFieldDefinition("Mystery", "Money", false, false, [])
        });

        var generator = CreateGenerator(temp.Path);
        var ex = Assert.Throws<InvalidOperationException>(() => generator.Generate(schema));
        Assert.Contains("Unsupported scalar type 'Money'", ex.Message);
    }

    private static CharismaSchema Parse(string schemaText)
    {
        var parser = new RoslynSchemaParser();
        return parser.Parse(schemaText);
    }

    private static CharismaGenerator CreateGenerator(string outputDirectory)
    {
        return new CharismaGenerator(new GeneratorOptions
        {
            RootNamespace = RootNamespace,
            GeneratorVersion = "tests",
            OutputDirectory = outputDirectory
        });
    }

    private static CharismaSchema BuildManualSchema(string modelName, IReadOnlyList<FieldDefinition> fields)
    {
        var model = new ModelDefinition(
            modelName,
            fields,
            Array.Empty<string>(),
            primaryKey: new PrimaryKeyDefinition(new[] { "Id" }));

        return new CharismaSchema(
            new Dictionary<string, ModelDefinition>(StringComparer.Ordinal) { [modelName] = model },
            new Dictionary<string, EnumDefinition>(StringComparer.Ordinal),
            new List<DatasourceDefinition>(),
            new List<GeneratorDefinition>());
    }
}

internal sealed class TempDirectory : IDisposable
{
    public TempDirectory()
    {
        Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "charisma-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path);
    }

    public string Path { get; }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(Path))
            {
                Directory.Delete(Path, recursive: true);
            }
        }
        catch
        {
            // Best effort cleanup in tests.
        }
    }
}
